-- Migration: AI graph slices
-- ===========================================================
-- Lightweight subgraph snapshots generated by AI to explain processes.
-- Stores references to nodes by oir_id (not UUIDs), making slices
-- portable and stable across re-indexes.

CREATE TABLE IF NOT EXISTS public.ai_graph_slices (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id        uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  session_id        uuid REFERENCES public.ai_sessions(id) ON DELETE SET NULL,
  user_id           uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Slice content
  title             text NOT NULL,
  explanation_md    text NOT NULL,         -- AI-generated markdown explanation

  -- Graph references (by oir_id for portability)
  node_oir_ids      text[] NOT NULL,       -- ordered list of node oir_ids in the slice
  edge_pairs        jsonb NOT NULL DEFAULT '[]',  -- [{"source":"oir_id1","target":"oir_id2","type":"calls"}]
  entry_point_oir_id text,                 -- the main node this slice starts from

  -- Metadata
  query_text        text,                  -- the question that generated this slice
  slice_type        text NOT NULL DEFAULT 'ai_generated'
    CHECK (slice_type IN ('ai_generated', 'user_saved', 'auto_explain')),
  tags              text[] NOT NULL DEFAULT '{}',

  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ai_graph_slices_project
  ON public.ai_graph_slices(project_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_graph_slices_session
  ON public.ai_graph_slices(session_id);

CREATE INDEX IF NOT EXISTS idx_ai_graph_slices_user
  ON public.ai_graph_slices(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_graph_slices_node_oir_ids
  ON public.ai_graph_slices USING gin (node_oir_ids);

CREATE INDEX IF NOT EXISTS idx_ai_graph_slices_tags
  ON public.ai_graph_slices USING gin (tags);

-- RLS
ALTER TABLE public.ai_graph_slices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access on ai_graph_slices"
  ON public.ai_graph_slices FOR ALL
  USING (auth.role() = 'service_role');

CREATE POLICY "Users can view own slices"
  ON public.ai_graph_slices FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own slices"
  ON public.ai_graph_slices FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own slices"
  ON public.ai_graph_slices FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own slices"
  ON public.ai_graph_slices FOR DELETE
  USING (auth.uid() = user_id);

-- Project members can view all slices in their project
CREATE POLICY "Project members can view project slices"
  ON public.ai_graph_slices FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.projects p
      JOIN public.workspace_members wm
        ON wm.workspace_id = p.workspace_id
        AND wm.user_id = auth.uid()
      WHERE p.id = ai_graph_slices.project_id
    )
  );

-- RPC: resolve a graph slice into actual node/edge data for rendering
CREATE OR REPLACE FUNCTION public.resolve_graph_slice(
  p_slice_id uuid
)
RETURNS TABLE(
  node_id     uuid,
  oir_id      text,
  type        public.oir_node_type,
  name        text,
  file_path   text,
  line_start  integer,
  line_end    integer,
  signature   text,
  doc_comment text,
  metadata    jsonb
)
LANGUAGE sql STABLE
AS $$
  SELECT
    cn.id,
    cn.oir_id,
    cn.type,
    cn.name,
    cn.file_path,
    cn.line_start,
    cn.line_end,
    cn.signature,
    cn.doc_comment,
    cn.metadata
  FROM public.ai_graph_slices s
  JOIN public.code_nodes cn
    ON cn.project_id = s.project_id
    AND cn.oir_id = ANY(s.node_oir_ids)
  WHERE s.id = p_slice_id;
$$;
